# https://supabase.com/docs/guides/cli/config
project_id = "xxmkcmgqgprmseoviilb"

[functions.invite-staff]
verify_jwt = false

[functions.update-staff-password]
verify_jwt = false

[functions.delete-staff-member]
verify_jwt = false

[functions.send-email-notifications]
verify_jwt = false

[functions.smtp-test]
verify_jwt = false

[functions.portal-auth]
verify_jwt = false
